### ISSUE TITLE
A roadmap question

### ISSUE THREAD

**Issue by mert-kurttutan** [tnltk/tnltk#4]
Hi Tarik,

Quick question about one potential future direction. As hinted in the readme.md, one goal is to provide a central library for pretrained weight, scripts etc for Turkish NLP.

I  am curious about the details of this part of the roadmap. Which models will you be starting to support, in which order? How to get support/sponsor for pretraining large models if need be. 

If it seems interesting, which probably it will be :), I would like to involve in the process as well.

**Comment by TarikKaanKoc** [comment]
Hi @mert-kurttutan,

Thanks for reaching out and expressing interest in our project to provide a central library for pretrained weights, scripts, etc for Turkish NLP.

Regarding the models, we haven't decided on the specific models yet. However, our priority is to apply various Turkish natural language processing methods in a step-by-step manner. This includes text summarization, sentiment analysis, and other Turkish natural language processing techniques. Our main focus will be on improving performance and scalability.

We also plan to collaborate with academic institutions and researchers to gather resources and expertise for pretraining these models.

We appreciate your offer to be involved in this process and we would love to have your support. Please let us know if you have any specific skills or resources that you can contribute to this project.

Thank you again for your interest in this project and we look forward to working with you.

Best Regards,
Tarık Kaan Koç.


**Note: Please don't close this issue, it's a common question mark on other developers' minds.**
